services:
  frontend:
    build: ./frontend/.
    ports:
      - 5000:5000
    depends_on:
      - backend
      - cache
  backend:
    build: ./backend/.
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=cache
      
  cache:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379