services:
  frontend:
    build: ./frontend/.
    ports:
      - 5000:5000
    depends_on:
      - backend
      - cache

  backend:
    build: ./backend/.
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=cache
      - POSTGRES_HOST=db
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=postgres-name
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: example
      POSTGRES_DB: postgres-name
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  cache:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
